name: CD Supuesto 8 - Guardian de Secretos

on: workflow_dispatch

jobs:
  despliegue-seguro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      # SUPUESTO 8: Inyectar contrase√±a desde los secretos de GitHub
      - name: Compilar con secreto inyectado
        run: mvn -B package -DskipTests
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}