name: CD Supuesto 2 - Almacen de Ejecutables

on: workflow_dispatch

jobs:
  almacenar-war:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Generar paquete WAR (omitiendo tests)
        run: mvn -B package -DskipTests

      # SUPUESTO 2: Sube el .war a GitHub Artifacts
      - name: Subir Ejecutable
        uses: actions/upload-artifact@v4
        with:
          name: paquete-final-war
          path: target/*.war