name: CD Supuesto 1 - Despliegue Manual

# SUPUESTO 1: Esto crea el bot√≥n "Run workflow" en GitHub
on: workflow_dispatch

jobs:
  generar-paquete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Compilar paquete (Manual)
        run: mvn -B package -DskipTests