name: CD Supuesto 6 - Despliegue SSH

on: workflow_dispatch

jobs:
  despliegue-remoto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Generar paquete WAR
        run: mvn -B package -DskipTests

      # SUPUESTO 6: Enviar por SCP usando llaves secretas
      - name: Copiar al servidor por SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "target/*.war"
          target: "/var/www/mi-aplicacion"